plugins {
    id 'com.android.application'
}

android {
    namespace 'com.oxclub.quizapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.oxclub.quizapp"
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName "3.3"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
}
